### PR TITLE
Added all test scripts for github, docker stats & deltas

### PR DESCRIPTION
**Pull request by rohit679**

### CODE REVIEW

**Comment by Annapooraniqxf2** [comment]
@PreedhiVivek 

I checked this pull request. I can see he didnt follow the spacing standards of Qxf2. when we run the requirements.txt files it's throwing some error. I couldnt run the test_stream_common_funtions for any of the directory(docker_deltas,docker_stats,github_stats,github_deltas). Maybe I need little help to run these files. Please let me know. 
If I have any errors while running do I need to fix those issues and push again?

**Comment by rohanj-qxf2** [comment]
@PreedhiVivek @Annapooraniqxf2 There were a couple of issues wrt package dependencies that were not added to the requirments.txt file and also some unwanted files like conf files were being imported which was not used in some of the tests.. I have fixed those up and have made tests running on the same branch - qelo-41-test-scripts-github-docker

**Docker delats and Docker stats tests**
Errors - 
1. ERROR: Invalid requirement: 'requests 2.24.0' (from line 1 of requirements.txt)
requests 2.24.0
2. ImportError: No module named mock
3. no module named boto3
4. no module named moto

Resolved it by adding those modules to the requirements.txt file
Test outputs
docker-deltas-test
docker-stats-test

**Github delta and Github stats tests**
Errors - 
1. =================================== ERRORS ====================================
_________________ ERROR collecting tests/test_github_stats.py _________________
tests\test_github_stats.py:12: in <module>
    import conf
conf.py:7: in <module>
    TOKEN = os.environ["ACCESS_KEY"]
..\venv-qxf2-lambda\lib\os.py:678: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'ACCESS_KEY'
___________ ERROR collecting tests/test_streams_common_functions.py ___________
tests\test_streams_common_functions.py:13: in <module>
    import conf
conf.py:7: in <module>
    TOKEN = os.environ["ACCESS_KEY"]
..\venv-qxf2-lambda\lib\os.py:678: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'ACCESS_KEY'
=========================== short test summary info ===========================
ERROR tests/test_github_stats.py - KeyError: 'ACCESS_KEY'
ERROR tests/test_streams_common_functions.py - KeyError: 'ACCESS_KEY'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 2 errors in 3.97s ==============================

Resolved the first error by removing 'import conf' from test files and also removed  the variable 'TOKEN' from the conf.py file since it was only used in stream_common_functions.py test, so just making a change in stream_common_functions.py as 
github_obj = Github(os.environ["ACCESS_KEY"]) resolved issue 

2. no module named github - Resolved by adding PyGithub to requirements.txt file
github-deltas-test
github-stats-test


Total list of files changed - 
image


**Pending**
When we run tests from the root directory there are 6 errors - 
image

**Comment by PreedhiVivek** [comment]
Yes @Annapooraniqxf2  and @rohanj-qxf2 This PR is a combined one of the other two PR's Hence those two PR's can e removed.
The code should be placed under qxf2-lambdas/qelo/<> where <> would be either store_github_stats or store_github_deltas etc accordingly

**Comment by rohanj-qxf2** [comment]
@Annapooraniqxf2 I have improved the pylint ratings for the tests now, can you check and review now

**Comment by Annapooraniqxf2** [comment]
> @Annapooraniqxf2 I have improved the pylint ratings for the tests now, can you check and review now

@rohanj-qxf2 
I checked it and I can see the huge difference. Shall we merge this into master now ?

**Comment by rohanj-qxf2** [comment]
@Annapooraniqxf2 THIS PR is open, can you merge it if it looks good?

**Comment by Annapooraniqxf2** [comment]
Yes sure will merge.

**Comment by Annapooraniqxf2** [comment]
@PreedhiVivek 
Shall I merge this fix into master or do you need to check anything else?

**Comment by PreedhiVivek** [comment]
@Annapooraniqxf2  and @rohanj-qxf2 ,
There are currently four separate lambdas (one per functionality) running in PROD everyday.
Hence, we will need to keep the code base as well into four separate folders under `qxf2-lambdas/qelo/` namely,
store_github_stats 
store_github_deltas
store_docker_stats
store_docker_deltas
containing the relevant scripts, and test scripts under a new `tests` folder under `qxf2-lambdas/qelo/` 

As there isn't any GitHub action defined at the moment for these four lambdas, this PR merge wouln't be auto-deployed  to the respective PROD lambdas, which is safe.

**Comment by Annapooraniqxf2** [comment]
> @Annapooraniqxf2 and @rohanj-qxf2 ,
> There are currently four separate lambdas (one per functionality) running in PROD everyday.
> Hence, we will need to keep the code base as well into four separate folders under `qxf2-lambdas/qelo/` namely,
> store_github_stats
> store_github_deltas
> store_docker_stats
> store_docker_deltas
> containing the relevant scripts, and test scripts under a new `/store_<respective_lambda>/` folder under `qxf2-lambdas/qelo/tests` folder.
> 
> As there isn't any GitHub action defined at the moment for these four lambdas, this PR merge wouln't be auto-deployed to the respective PROD lambdas, which is safe.

So @PreedhiVivek Shall We merge into master? or do I need to do the changes like change the name with store_ and merge it.

**Comment by PreedhiVivek** [comment]
@Annapooraniqxf2 Please ensure all scripts of this PR are placed under  `qxf2-lambdas/qelo/` folder and go ahead with the merge.
Renaming of folders can be ignored.

**Comment by qxf2** [comment]
Closing this PR since it is obsolete.

**Pull request closed without merging**
