### PR TITLE
Add access keys authentication

### PR DESCRIPTION
**Pull request by sravantit25**

### CODE REVIEW

**Comment by PreedhiVivek** [comment]
Thanks @sravantit25 for taking up the refactoring of lambda. It was time for it to be done.
My observations:
- Naming can be more specific as we have one common conf. Like, REMOTEIT_HOST instead of HOST. Prefix env vars with context.
- Use get method while accessing dicts across. Example line# 15 in raspberry_helper.py
- Exception handling to be added to Skpe sender 
- I still find certain methods lengthier. You could move, say the initializations, to a separate function say setup(). Overall ensuring single responsibility principle making functions smaller and crispier. Radon runs if not done, would guide with this.

**Review by PreedhiVivek — APPROVED** [review]

**Comment by mohanqxf2** [comment]
thank you @sravantit25 its an excellent work on refactoring the lambda. I do not have anything specific, Preedhi has covered all the changes needed we can move this PR forward.

**Comment by sravantit25** [comment]
> * Naming can be more specific as we have one common conf. Like, REMOTEIT_HOST instead of HOST. Prefix env vars with context.
> * Use get method while accessing dicts across. Example line# 15 in raspberry_helper.py
> * Exception handling to be added to Skpe sender
> * I still find certain methods lengthier. You could move, say the initializations, to a separate function say setup(). Overall ensuring single responsibility principle making functions smaller and crispier. Radon runs if not done, would guide with this.

Thank you Preedhi for the review. I have fixed points 1 and 3. I will let further refactoring (points 2 and 4) be done in next version or let someone else give it a try.

**Comment by sravantit25** [comment]
> thank you @sravantit25 its an excellent work on refactoring the lambda. I do not have anything specific, Preedhi has covered all the changes needed we can move this PR forward.

Thank you Mohan! :)

**Pull request merged**
